semantic-release
growlerapp/webapp pull request #26
Opened 2019-05-22 01:35 UTC by lgaticaq

Esta pensado para hacer el release solo en master. Ademas esta pendiente agregar las variables de entorno necesarias en travis para que funcione correctamente semantic-release.

- Se agrega semantic-release para el versionamiento semantico.
- Se integra travis para gatillar lint, test y release.
- Se agregaron devDependencies y peerDependencies no declaradas.
- Se deshabilita package-lock.json.

2019-05-22 01:35 UTC, lgaticaq commented
Deploy preview for *growlerapp* processing.

Building with commit e33f7362c78f4bf03fb953d207c52fb61ab8190d

https://app.netlify.com/sites/growlerapp/deploys/5ce4a772633ea00008555d28

2019-05-22 01:46 UTC, raulghm commented
@lgaticaq actualmente estoy usando yarn, seria recomendable usar npm solamente?
lo digo por los locks files

2019-05-22 02:26 UTC, juanbrujo commented
yarn, gracias por ni incluirme :qls:

2019-05-22 13:59 UTC, lgaticaq commented
@raulghm da un poco lo mismo cual usar. Es básicamente cosa de gustos. Y ya que ambos prefieren yarn es mejor seguir usando eso.

2019-05-22 14:01 UTC, raulghm approved these changes

2019-05-23 01:23 UTC, juanbrujo requested changes
conflicto

2019-05-23 20:49 UTC, juanbrujo approved these changes

2019-05-24 01:27 UTC, closed without merging

2019-05-24 05:03 UTC, lgaticaq commented
@raulghm porque fue cerrado este PR?

2019-05-24 13:29 UTC, raulghm commented
@lgaticaq no caché que se cerro por que elimine la rama dev, esto estaba apuntando a dev :/

2019-05-24 14:31 UTC, lgaticaq commented
cierto, dale hago el PR a master