fix: refresh geo detection
growlerapp/webapp pull request #43
Opened 2019-05-28 00:46 UTC by raulghm

Mejora la lógica y la acción cuando el usuario refresca la aplicación, ahora actualiza la geo (lat, long) por lo cual al cambiar de posicion tambien afecta los resultados de los bares encontrados.

2019-05-28 00:46 UTC, lgaticaq commented
Deploy preview for *growlerapp* processing.

Building with commit ad5e0fb06a580a2a91b4a80635a74b0538f4adb1

https://app.netlify.com/sites/growlerapp/deploys/5cec84f54d3e1f0009dac0f8

2019-05-28 20:45 UTC, lgaticaq requested changes

2019-05-28 20:45 UTC, lgaticaq commented on src/user.js
> +  return JSON.parse(localStorage.getItem('userGeoData'))
@raulghm esto es susceptible a errores si por alguna razón el contenido de `userGeoData` no es un json like

2019-05-28 20:45 UTC, lgaticaq commented on src/user.js
> + * @return {object} user geo data
@raulghm esto debe ser:

```suggestion
 * @return {Promise<object>} user geo data
```

2019-05-29 15:03 UTC, juanbrujo commented on src/user.js
> +  return JSON.parse(localStorage.getItem('userGeoData'))
no veo porque no deberia serlo, que caso borde piensas?

2019-05-30 14:16 UTC, juanbrujo approved these changes

2019-05-30 14:31 UTC, raulghm reviewed
Se mejora en metodo checkUserGeoData 👌

2019-05-30 14:31 UTC, raulghm commented on src/user.js
>  const checkUserGeoData = () => {
Preferi dejar la comprobacion de integridad de la data en esta funcion, que opinan? @lgaticaq @juanbrujo

2019-05-30 15:15 UTC, lgaticaq requested changes

2019-05-30 15:15 UTC, lgaticaq commented on src/user.js
> +  return JSON.parse(localStorage.getItem('userGeoData'))
@raulghm sigue susceptible a lanzar un error esta función. Debe estar envuelta en un try/catch o bien dejar el try/catch cuando sea llamada.

```suggestion
  try {
    return JSON.parse(localStorage.getItem('userGeoData'))
  } catch (err) {
    return null
  }
```

2019-06-16 21:38 UTC, merged

2019-06-17 21:33 UTC, juanbrujo commented on src/user.js
>  const checkUserGeoData = () => {
👍